---
title: "Exploratory analysis 2"
output: html_document
date: "2024-01-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
par.ori <- par(no.readonly = TRUE)
require(geoR)

ls()
data(s100)
ls()
data(SIC)
ls()

## create geodata
require(MASS)
data(topo)
topo
gtopo <- as.geodata(topo)
gtopo
args(as.geodata)

# download data
cru <- read.geodata("http://www.leg.ufpr.br/geoR/tutorials/datasets/Cruciani.dat", head=T, row.names=1) 
cru
cru.borda <-  read.table("http://www.leg.ufpr.br/geoR/tutorials/datasets/Cruciani.border", head=T)[,2:3]
cru.borda <- rbind(cru.borda, cru.borda[1,])

## plot
plot(cru, bord = cru.borda)
args(plot.geodata)
plot(cru, bord=cru.borda, lambda=0)
hist(cru$data, main="", xlab="K")
hist(log(cru$data), main="", xlab="log(K)")

## points
points(cru, bord=cru.borda)
args(points.geodata)
points(cru, bord=cru.borda, cex.min=1, cex.max=1, pt.div="quartile")
points(cru, bord=cru.borda, cex.min=1, cex.max=1, col=gray(seq(0.9,0,l=length(cru$data))))
points(cru, bord=cru.borda, cex.min=1, cex.max=1, col=gray(seq(0.9,0,l=length(cru$data))), xla="Coord X", ylab="Coord Y")
points(cru, lambda=0, bord=cru.borda)
points(cru, lambda=0, bord=cru.borda, cex.min=1, cex.max=1, pt.div="quartile")
points(cru, lambda=0, bord=cru.borda, cex.min=1, cex.max=1, col=gray(seq(0.9,0,l=length(cru$data))))

## Variogram
cru.v1 <-  variog(cru)
plot(cru.v1)
cru.v1
names(cru.v1)
args(variog)
cru.cl1 <- variog(cru, option = "cloud")
plot(cru.cl1)
cru.v2 <- variog(cru, lambda = 0)
plot(cru.v2)
cru.cl2 <- variog(cru, lambda = 0, option = "cloud")
plot(cru.cl2)
cru.v3 <- variog(cru, lambda = 0, max.dist=9)
plot(cru.v3)
cru.v4 <- variog(cru, lambda = 0, uvec=seq(0,9,l=8))
plot(cru.v4)
cru.v5 <- variog(cru, lambda = 0, uvec=seq(0,12,l=8))
plot(cru.v5)
cru.v6 <- variog(cru, lambda = 0, uvec=seq(0,15,l=8))
plot(cru.v6)
cru.v <- variog(cru, lambda = 0, uvec=seq(0,9,l=8), bin.cl=T)
plot(cru.v)
plot(cru.v, bin.cloud = T)
cru.mv <- variog(cru, lambda = 0, uvec=seq(0,9,l=8), est="mod")
plot(cru.mv)
cru.v <- variog(cru, lambda = 0, uvec=seq(0,9,l=8), bin.cl=T)
cru.env <- variog.mc.env(cru, obj.variog = cru.v)
plot(cru.v, env = cru.env) 

```
